### ISSUE TITLE
Consider adding this in next/examples

### ISSUE THREAD

**Issue by romainquellec** [dabit3/next-apollo-appsync#5]
Everything is in the title :)

**Comment by romainquellec** [comment]
Closing. This will never get any response :(

**Comment by romainquellec** [comment]
I'm reopening this as this repo can be maintain by the next community. @dabit3

**Comment by dabit3** [comment]
Hey, I'd love to move this into some community-based repo for the NextJS community.

**Comment by romainquellec** [comment]
Before pushing something into next repo, we should update this with last version of next.
